
### Create a new User
POST http://localhost:3003/signup
Content-Type: application/json

{
    "name":"Breno Smith",
    "email":"brenosmith@gmail.com",
    "password": "1234567",
    "role": "NORMAL"
}

### Login User
GET http://localhost:3003/login
Content-Type: application/json

{    
    "email":"biancasmith@gmail.com",
    "password": "1234567"   
}

### All Users
GET http://localhost:3003/user/allusers
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjcyMTYxYTQ1LWE0NmItNDhjNi05OTBjLWNhYTM0OGFlMmIwMCIsImlhdCI6MTY3NjMxNzc1OSwiZXhwIjoxNjc2MzIxMzU5fQ.S_XnE3KmR9cnAXbwwKPMr9JB8SlD0JZovNX9m5rLDaI

### Profile
GET http://localhost:3003/user/profile
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjcyMTYxYTQ1LWE0NmItNDhjNi05OTBjLWNhYTM0OGFlMmIwMCIsImlhdCI6MTY3NjMxNzc1OSwiZXhwIjoxNjc2MzIxMzU5fQ.S_XnE3KmR9cnAXbwwKPMr9JB8SlD0JZovNX9m5rLDaI

### Profile User
GET http://localhost:3003/user/69032ad3-fc60-444a-820f-b3b6d14f94d1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjcyMTYxYTQ1LWE0NmItNDhjNi05OTBjLWNhYTM0OGFlMmIwMCIsImlhdCI6MTY3NjMxNzc1OSwiZXhwIjoxNjc2MzIxMzU5fQ.S_XnE3KmR9cnAXbwwKPMr9JB8SlD0JZovNX9m5rLDaI

### Create recipe
POST http://localhost:3003/recipe
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjcyMTYxYTQ1LWE0NmItNDhjNi05OTBjLWNhYTM0OGFlMmIwMCIsImlhdCI6MTY3NjMxNzc1OSwiZXhwIjoxNjc2MzIxMzU5fQ.S_XnE3KmR9cnAXbwwKPMr9JB8SlD0JZovNX9m5rLDaI

{
	"title": "BOLO DE MACAXEIRA SIMPLES",
	"description": "2 kg de macaxeira ralada, 6 ovos, 6 xícaras de açúcar, 6 colheres bem generosa de manteiga, 200 g de coco ralado, 1 pitada de sal, 1 colher de fermento"
}

### Return recipe
GET http://localhost:3003/recipe/1769422f-3caa-4f63-a2dd-affc0def060a
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjcyMTYxYTQ1LWE0NmItNDhjNi05OTBjLWNhYTM0OGFlMmIwMCIsImlhdCI6MTY3NjMxNzc1OSwiZXhwIjoxNjc2MzIxMzU5fQ.S_XnE3KmR9cnAXbwwKPMr9JB8SlD0JZovNX9m5rLDaI

### Criate Followers
POST http://localhost:3003/user/follow
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjcyMTYxYTQ1LWE0NmItNDhjNi05OTBjLWNhYTM0OGFlMmIwMCIsImlhdCI6MTY3NjMxNzc1OSwiZXhwIjoxNjc2MzIxMzU5fQ.S_XnE3KmR9cnAXbwwKPMr9JB8SlD0JZovNX9m5rLDaI

{
    "userToFollowId":"7cfcd5b0-59ca-41d6-a4ae-ae2ded0db51c"
}

### Unfollow
DELETE http://localhost:3003/user/unfollow
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjcyMTYxYTQ1LWE0NmItNDhjNi05OTBjLWNhYTM0OGFlMmIwMCIsImlhdCI6MTY3NjMxNzc1OSwiZXhwIjoxNjc2MzIxMzU5fQ.S_XnE3KmR9cnAXbwwKPMr9JB8SlD0JZovNX9m5rLDaI

{
    "userToUnfollowId":"7cfcd5b0-59ca-41d6-a4ae-ae2ded0db51c"
}

### Create a new Friendship
POST http://localhost:3003/friendship/create
Content-Type: application/json
Authorization: 1675001631299


### Delete Friendship
DELETE http://localhost:3003/friendship
Content-Type: application/json
Authorization: 1675001631299

{
    "friendId":"1675019596015"
}

### Return Feeds freands
GET http://localhost:3003/post/getfeedsfreands
Content-Type: application/json
Authorization: fde08a25-cb5c-4948-bb59-693eb726721d

### return feed by type 
GET http://localhost:3003/post/getfeeds
Content-Type: application/json

{
    "type":"normal"
}

### Like Post
POST http://localhost:3003/like/create
Content-Type: application/json
Authorization: 1675001631299

{
    "postId":"1675379034720"
}

### Delete Like Post
DELETE  http://localhost:3003/like
Content-Type: application/json
Authorization: 1675001631299

{
    "postId":"1675379034720"
}

### Comment Post
POST   http://localhost:3003/comments
Content-Type: application/json
Authorization: 1675001631299

{
    "comment":"Linda foto",
    "postId":"1675379034720"
}